version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - "5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
